### ISSUE TITLE
id in metadata.yml ergänzen

### ISSUE THREAD

**Issue by mirjan-hoffmann** [joerglohrer/Bibelfussball#5]
Bitte die URL zur Resource im Feld `id` in der metadata.yml ergänzen. Im OERSI wird sonst als Default-Wert die URL zur Default GitHub-Page verwendet.

Vgl. https://oersi.org/resources/aHR0cHM6Ly9qb2VyZ2xvaHJlci5naXRodWIuaW8vQmliZWxmdXNzYmFsbA==

**Comment by joerglohrer** [comment]
Hi @mirjan-hoffmann vielen Dank - ich habe direkt überarbeitet und aktualisiert. 
Allerdings ist es jetzt doppelt auf OERSI:
- Neu: https://oersi.org/resources/aHR0cHM6Ly9naXRodWIuY29tL2pvZXJnbG9ocmVyL0JpYmVsZnVzc2JhbGw=
- Alt: https://oersi.org/resources/aHR0cHM6Ly9qb2VyZ2xvaHJlci5naXRodWIuaW8vQmliZWxmdXNzYmFsbA==
Habe ich was falsch gemacht?

**Comment by joerglohrer** [comment]
@mirjan-hoffmann ok - der alte Link ist jetzt 404, also entfernt. damit kann ich schließen, oder?

**Comment by mirjan-hoffmann** [comment]
Ja, Danke. Alte Links werden einmal wöchtentlich aufgeräumt
